name: Update Papers

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run arXiv scraper
      run: |
        python scripts/scrape_arxiv.py
    
    - name: Merge papers
      run: |
        python scripts/merge_papers.py

    - name: Update README
      run: |
        python scripts/update_readme.py

    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global pull.rebase true
        git config --global rebase.autoStash true

    - name: Commit local changes
      run: |
        git add .
        git commit -m "Automatically update papers and README" || echo "No changes to commit"

    - name: Pull remote changes and rebase
      run: |
        git pull --rebase origin main

    - name: Push changes
      run: |
        git push origin main
